### ISSUE TITLE
project formalisation

### ISSUE THREAD

**Issue by crystalcheong** [mawsters/docs#2]
> [!NOTE]  
> ⏪ Recap: [project conceptualisation #1](https://github.com/mawsters/docs/issues/1)
> 📝 Editable [Minutes 1.1](https://docs.google.com/document/d/1VGEybvN7Ca27xqw2t2QSijuZs7wsPDvi-K0J5UcMo3U/edit?usp=sharing)<br/>

discussion topics
- [x] Dev: Research on suitable API endpoints, determine project feasibility
- [x] Docs: Initialise SRS #6 
  - [x] Outline requirements
  - [x] Draft use-case diagrams #4 
- [x] Admin: Submit project proposal #3 
- [x] Admin: Ensure all created Wiki account

---

- 📝 Complied [Minutes 1.1](https://github.com/mawsters/docs/blob/deliverables/1/Deliverables/Lab%201/Meeting-Minutes-1.1.pdf)

**Comment by crystalcheong** [comment]
- [X] Dev: Research on suitable API endpoints, determine project feasibility
  > External APIs
  > - Searching:[Google Books](https://developers.google.com/books/docs/v1/)
  > - Bestsellers Lists: [NYT](https://developers.google.com/books/docs/v1/)

  > API (backend)
  > - User: CRUD (handled by [`clerkjs sdk`](https://clerk.com/docs/references/backend/overview)
  > - Auth/Shelves (completed, reading, to read): CRUD
  > - Auth/Reviews & Ratings: CRUD
  > - Book/Search (using Google Books): R
  > - Book/Recommendations: R
